<a href="https://colab.research.google.com/github/dshree-21/Women-Cloth-Reviews-Prediction/blob/main/WomenCloth.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd

In [66]:
import numpy as np

In [67]:
import matplotlib.pyplot as plt

In [68]:
import seaborn as sns

## **Import Dataset**

In [69]:
df = pd.read_csv("https://raw.githubusercontent.com/YBIFoundation/ProjectHub-MachineLearning/main/Women%20Clothing%20E-Commerce%20Review.csv")

In [70]:
df.head()

Clothing ID  Age                    Title  \
0          767   33                      NaN   
1         1080   34                      NaN   
2         1077   60  Some major design flaws   
3         1049   50         My favorite buy!   
4          847   47         Flattering shirt   

                                              Review  Rating  Recommended  \
0  Absolutely wonderful - silky and sexy and comf...       4            1   
1  Love this dress!  it's sooo pretty.  i happene...       5            1   
2  I had such high hopes for this dress and reall...       3            0   
3  I love, love, love this jumpsuit. it's fun, fl...       5            1   
4  This shirt is very flattering to all due to th...       5            1   

   Positive Feedback        Division Department   Category  
0                  0       Initmates   Intimate  Intimates  
1                  4         General    Dresses    Dresses  
2                  0         General    Dresses    Dresses  
3                  0  General Petite    Bottoms      Pants  
4                  6         General       Tops    Blouses

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Clothing ID        23486 non-null  int64 
 1   Age                23486 non-null  int64 
 2   Title              19676 non-null  object
 3   Review             22641 non-null  object
 4   Rating             23486 non-null  int64 
 5   Recommended        23486 non-null  int64 
 6   Positive Feedback  23486 non-null  int64 
 7   Division           23472 non-null  object
 8   Department         23472 non-null  object
 9   Category           23472 non-null  object
dtypes: int64(5), object(5)
memory usage: 1.8+ MB


In [9]:
df.shape

(23486, 10)

### **Missing Values**

Remove missing values in Review columns with No Review text

In [72]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                845
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [73]:
df[df['Review']==""] = np.NaN

In [74]:
df['Review'].fillna("No review is given", inplace=True)

In [75]:
df.isna().sum()

Clothing ID             0
Age                     0
Title                3810
Review                  0
Rating                  0
Recommended             0
Positive Feedback       0
Division               14
Department             14
Category               14
dtype: int64

In [76]:
df['Review']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review, Length: 23486, dtype: object

## **Defining Target (y) and Feature (X)**

In [77]:
df.columns

Index(['Clothing ID', 'Age', 'Title', 'Review', 'Rating', 'Recommended',
       'Positive Feedback', 'Division', 'Department', 'Category'],
      dtype='object')

In [78]:
X= df['Review']

In [79]:
y = df['Rating']

In [80]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

## **Train Test Split**

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)

In [90]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Features Text Conversions to Tokens**

In [91]:
from sklearn.feature_extraction.text import CountVectorizer

In [92]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [93]:
X_train= cv.fit_transform(X_train)

In [94]:
cv.get_feature_names_out()

array(['10 12', '10 bought', '10 fit', ..., 'yellow color', 'yoga pants',
       'zipper little'], dtype=object)

In [95]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [96]:
X_test=cv.fit_transform(X_test)

In [97]:
cv.get_feature_names_out()

array(['10 12', '10 dress', '10 fit', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [98]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

# **Get Model Train**

In [99]:
from sklearn.naive_bayes import MultinomialNB

In [100]:
model=MultinomialNB()

In [101]:
model.fit(X_train,y_train)

MultinomialNB()

# **Get Model Prediction**

In [102]:
y_pred=model.predict(X_test)

In [103]:
y_pred.shape

(7046,)

In [104]:
y_pred

array([5, 2, 4, ..., 5, 1, 5])

# **Get Probability Of Each Predicted Class**

In [105]:
model.predict_proba(X_test)

array([[0.10226629, 0.0269384 , 0.25269884, 0.06708817, 0.55100831],
       [0.12853608, 0.33847046, 0.10000821, 0.16639435, 0.2665909 ],
       [0.04530748, 0.05490702, 0.19180836, 0.40611124, 0.3018659 ],
       ...,
       [0.22718349, 0.14038932, 0.19735435, 0.00832154, 0.42675129],
       [0.7823138 , 0.04269121, 0.03252024, 0.10419279, 0.03828196],
       [0.01243316, 0.00147378, 0.05953924, 0.00629346, 0.92026036]])

# **Get Model Evaluation**

In [106]:
from sklearn.metrics import confusion_matrix,classification_report

In [107]:
print(confusion_matrix(y_test,y_pred))

[[  25   26   39   56  107]
 [  49   50   71   88  212]
 [  76   95  137  174  379]
 [ 156  131  199  341  696]
 [ 341  282  334  808 2174]]


In [108]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.04      0.10      0.06       253
           2       0.09      0.11      0.09       470
           3       0.18      0.16      0.17       861
           4       0.23      0.22      0.23      1523
           5       0.61      0.55      0.58      3939

    accuracy                           0.39      7046
   macro avg       0.23      0.23      0.22      7046
weighted avg       0.42      0.39      0.40      7046



# **Recategories Ratings as Poor (0) and Good (1)**

In [109]:
df['Rating'].value_counts()

Rating
5    13131
4     5077
3     2871
2     1565
1      842
Name: count, dtype: int64

**Re-Rating as 1,2,3 as 0 and 4, 5 as 1**

In [110]:
df.replace({'Rating:':{1:0,2:0,3:0,4:1,5:1}},inplace=True)

In [111]:
y=df['Rating']

In [112]:
X=df['Review']

# **Train Test Split**

In [113]:
from sklearn.model_selection import train_test_split

In [114]:
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,stratify=y,random_state=2529)

In [115]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((16440,), (7046,), (16440,), (7046,))

# **Get Feature Texts Conversion to Tokens**

In [116]:
from sklearn.feature_extraction.text import CountVectorizer

In [117]:
cv=CountVectorizer(lowercase=True,analyzer='word',ngram_range=(2,3),stop_words='english',max_features=5000)

In [118]:
X_train= cv.fit_transform(X_train)

In [119]:
X_test=cv.fit_transform(X_test)

# **Get Model Re-Train**

In [120]:
from sklearn.naive_bayes import MultinomialNB

In [121]:
model=MultinomialNB()

In [122]:
model.fit(X_train,y_train)

MultinomialNB()

# **Get Model Prediction**

In [123]:
y_pred=model.predict(X_test)

In [124]:
y_pred.shape

(7046,)

In [125]:
y_pred

array([5, 2, 4, ..., 5, 1, 5])

# **Get Model Evaluation**

In [126]:
from sklearn.metrics import confusion_matrix,classification_report

In [127]:
print(confusion_matrix(y_test,y_pred))

[[  25   26   39   56  107]
 [  49   50   71   88  212]
 [  76   95  137  174  379]
 [ 156  131  199  341  696]
 [ 341  282  334  808 2174]]


In [128]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.04      0.10      0.06       253
           2       0.09      0.11      0.09       470
           3       0.18      0.16      0.17       861
           4       0.23      0.22      0.23      1523
           5       0.61      0.55      0.58      3939

    accuracy                           0.39      7046
   macro avg       0.23      0.23      0.22      7046
weighted avg       0.42      0.39      0.40      7046

